apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::851297221072:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1MT20MFH4KEDN
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::851297221072:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-07T13:31:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2261"
  uid: 506756b4-a765-4885-b22d-54e2b475a337
